import localFont from "next/font/local";
import { Suspense } from "react";
import ErrorBoundary from "./components/ErrorBoundary";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "LUMINEERS WEB",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",  // Path to your image in the public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="A vibrant travel blog platform for explorers to share journeys, stories, and inspiration. Discover authentic travel experiences and connect with fellow adventurers." />
        <meta name="keywords" content="travel, blog, explorer, journey, adventure, stories, lumineers" />
        <meta name="author" content="Lumineers Web" />
        <meta name="robots" content="index, follow" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#3b82f6" />
        {/* Open Graph Meta Tags */}
        <meta property="og:title" content="LUMINEERS WEB" />
        <meta property="og:description" content="Share and discover travel stories from explorers around the world. Chronicle your journey and inspire others." />
        <meta property="og:image" content="/favicon.svg" />
        <meta property="og:url" content="https://lumineers-web.com" />
        <meta property="og:type" content="website" />
        {/* Twitter Card Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="LUMINEERS WEB" />
        <meta name="twitter:description" content="Share and discover travel stories from explorers around the world." />
        <meta name="twitter:image" content="/favicon.svg" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ErrorBoundary>
          <Suspense fallback={<div className="min-h-screen flex items-center justify-center">Loading...</div>}>
            {children}
          </Suspense>
        </ErrorBoundary>
      </body>
    </html>
  );
}
